### ISSUE TITLE
Installation does not require straight

### ISSUE THREAD

**Issue by brittAnderson** [SqrtMinusOne/reverso.el#4]
`use-package` now has the capacity to install a package from github directly and this has been merged into the most recent emacs. I just installed your excellent package (I am using emacs 30) with the following in my `init.el`:

    (use-package reverso
    :vc (:url "https://github.com/SqrtMinusOne/reverso.el.git"))

This might make it easier for users to use your package?

**Comment by SqrtMinusOne** [comment]
Well, I didn't say the package works only with straight.el, but I've added the point about `vc` in the referenced commit anyway, so thanks.

I'll probably submit the package to MELPA in the near future. I hadn't done this initially because I didn't think that the API is going to remain stable for so long... Hopefully it's not a Thanksgiving turkey fallacy.

**Comment by SqrtMinusOne** [comment]
Added to MELPA.
